# Generated by Django 4.0.4 on 2022-05-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
